services:
  mysql:
    image: mysql:8.0
    container_name: plate-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: plate_verification
      # (Opcional) crea un usuario app:
      # MYSQL_USER: app
      # MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: [plate_net]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: plate-phpmyadmin
    environment:
      PMA_HOST: plate-mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks: [plate_net]
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: plate-backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
    networks: [plate_net]
    command: sh -c "npm run dev"
    restart: unless-stopped
    # (Opcional) healthcheck simple al health endpoint:
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/api/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    build: ./frontend
    container_name: plate-frontend
    environment:
      - VITE_API_URL=http://localhost:3001
    ports:
      - "5174:5173"   # frontend en 5174 por fuera
    depends_on:
      backend:
        condition: service_started
    networks: [plate_net]
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  plate_net:
