version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: plate-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: plate_verification
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: [plate_net]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: plate-phpmyadmin
    environment:
      PMA_HOST: plate-mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks: [plate_net]

  backend:
    build: ./backend
    container_name: plate-backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks: [plate_net]
    command: sh -c "npm run dev"

  frontend:
    build: ./frontend
    container_name: plate-frontend
    environment:
      - VITE_API_URL=http://localhost:3001
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks: [plate_net]

volumes:
  mysql_data:

networks:
  plate_net:
