services:
  mysql:
    image: mysql:8.0
    container_name: plate-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: plate_verification
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: plate-backend
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=plate_verification
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - JWT_SECRET=pon_un_secreto_real_aqui
      - PLATE_RECOGNIZER_API_KEY=your_api_key_here
      - PORT=5000
      - NODE_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    command: sh -c "npm run dev"
    # Opcional:
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: plate-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  mysql_data:
